---
title: "MDRO Screening Analysis"
format: html
editor: visual
date: now
---

```{r loading pac and data clean, include=FALSE}
library(tidyverse) #Tidyverse is essential for many functions here
library(Hmisc) #Needed for the cleaning script that redcap uses
library(haven) #In case we need to load SAS data
library(gt) #Used for table generation

source("Cleaning.r",
       local = knitr::knit_global()) #Automatically loads the cleaning script that Redcap produces

settingname <- c("Acute care hospital", 
                 "Long-term acute care hospital", 
                 "Ventilator-capable skilled nursing facility", 
                 "Skilled nursing facility/nursing home", 
                 "Assisted living facility/adult care home", 
                 "Dialysis", 
                 "Other",
                 ".", 
                 "Unknown") #Lets do some cleanup while were here, this is a list of names of the actual settings our screenings took place in. 

data$setting <- settingname[data$setting] #this replaces the names in the dataset using the settingname list. Order matters 1 = first name in list, 2 = 2nd name in list so on...

#separate between screen data and case data
screendata <- data %>% 
  filter(redcap_repeat_instrument == "screening_abstraction") #We need to separate screen data from case data. This is screen data table.

casedata <- data %>% 
  filter(redcap_repeat_instrument == "case_abstraction") #Case data table generated using same method as before.

#If screendata has casedata

screendata <- screendata %>% 
  mutate(positive_id = ifelse(screening_id %in% casedata$screening_id, 
                              "Positive_screen", 
                              "Negative_screen")) #We need to create an ID that determines whether a screen found a positive during the first PPS. This looks for matching IDs between the screen data and case data tables. No cases would ever be extracted from negative screens. If there is a match we assign that screen as positive otherwise negative.

screendata <- screendata[,c(1:110, 258)] #Cuts out nonsense columns from the redcap table that we dont need for this analysis
  
tableclean <- function(x, yr, ...){
  
  group_<-enquos(...)
  
  x %>% 
  filter(!year %in% yr & 
         redcap_repeat_instrument == "screening_abstraction") %>% 
  group_by(!!!group_) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = positive_id, 
              values_from = n) %>% 
  replace(is.na(.), 
          0) %>% 
  mutate(total = sum(c_across()),
         !!"Negative_screen" := if("Negative_screen" %in% colnames(.))
         {
           Negative_screen
         } else {0}, #This line is saying if there is no negative screen column, make one and insert a 0, otherwise leave it the same
         Negative_perc = (Negative_screen/total)*100,
         Negative_perc = round(Negative_perc, 
                               2),
         !!"Positive_screen" := if("Positive_screen" %in% colnames(.))
         {
           Positive_screen
         } else {0}, #This line is saying if there is no Positive screen column, make one and insert a 0, otherwise leave it the same
         Positive_perc = (Positive_screen/total)*100,
         Positive_perc = round(Positive_perc, 2))
} #Function to make table output easier. This will save us lots of time later on
#x = dataset (i.e. screendata)
#yr = year to not include (numeric year)
#... = groupby groups (i.e. setting, positive_id)
#honestly this function is a mess and is very specific.

```

## What is the proportion of initial screenings that identify positives (of the same organism or carbapenemase)?

### Table 1

#### Raw Table 1

```{r, include=FALSE}
totalcount <- screendata %>% tableclean(2019, positive_id) #shows the power of table function we made, gets total positive and negative screens and gets percents.
totalcount$summary <- "summary" #We need a column that shows that this is a summary table.

#Setting Counts - type of healthcare facility where screening occurred

settingcount <- tableclean(screendata, 2019, setting, positive_id)

settingcount

#screening type
ppsonly <- screendata %>% 
  filter(screen_type___1 == 1, screen_type___2 == 0, screen_type___3 == 0, screen_type___7 == 0, screen_type___9==0) %>% 
  tableclean(2019, positive_id)
ppsonly$screentype <- "PPS only"

contactonly <- screendata %>% 
  filter(screen_type___1 == 0, screen_type___2 == 1, screen_type___3 == 0, screen_type___7 == 0, screen_type___9==0) %>% 
  tableclean(2019, positive_id)
contactonly$screentype <- "Contact only"

flagonly <- screendata %>% 
  filter(screen_type___1 == 0, screen_type___2 == 0, screen_type___3 == 1, screen_type___7 == 0, screen_type___9==0) %>% 
  tableclean(2019, positive_id)
flagonly$screentype <- "Flag only"

flagscreen <- screendata %>% 
  filter(screen_type___1 == 1, screen_type___2 == 0, screen_type___3 == 1, screen_type___7 == 0, screen_type___9==0) %>% 
  tableclean(2019, positive_id)
flagscreen$screentype <- "PPS and Flag"

flagcontact <- screendata %>% 
  filter(screen_type___1 == 0, screen_type___2 == 1, screen_type___3 == 1, screen_type___7 == 0, screen_type___9==0) %>% 
  tableclean(2019, positive_id)
flagcontact$screentype <- "Flag and Contact"

ppscontact <- screendata %>% 
  filter(screen_type___1 == 1, screen_type___2 == 1, screen_type___3 == 0, screen_type___7 == 0, screen_type___9==0) %>% 
  tableclean(2019, positive_id)
ppscontact$screentype <- "PPS and Contact"

otherunknown <- screendata %>% 
  filter(screen_type___7 == 1 |screen_type___9==1) %>% 
  tableclean(2019, positive_id)
otherunknown$screentype <- "Other or Unknown"

screentypedata <- rbind(ppsonly, contactonly, flagonly, ppscontact, flagscreen, flagcontact, otherunknown)


#organism count


screendataorg <- screendata %>% 
  pivot_longer(cols = starts_with("organism__"),
                            names_to = "organism",
                            values_to = "organism_value",
                            values_transform = list(organism_value = as.integer)) %>% 
  mutate(organism = case_match(organism, "organism___1" ~ "C. auris",
                                     "organism___2" ~ "E. coli",
                                     "organism___3" ~ "E. cloacae",
                                     "organism___4" ~ "E. aerogenes",
                                     "organism___5" ~ "K. pneumoniae",
                               "organism___6" ~ "K. oxytoca",
                               "organism___7" ~ "P. aeruginosa",
                               "organism___8" ~ "A. baumanii",
                               "organism___9" ~ "No org id",
                               "organism___10" ~ "Other")) %>% 
  filter(organism_value==1) %>% 
  tableclean(2019, organism, positive_id)

screendataorg

#cpase
screendatacpase <- screendata %>% 
  pivot_longer(cols = starts_with("cpase__"),
                            names_to = "cpase",
                            values_to = "cpase_value",
                            values_transform = list(cpase_value = as.integer)) %>% 
  mutate(cpase = case_match(cpase, "cpase___1" ~ "KPC",
                                     "cpase___2" ~ "NDM",
                                     "cpase___3" ~ "OXA23/24",
                                     "cpase___4" ~ "OXA-48",
                                     "cpase___5" ~ "VIM",
                               "cpase___6" ~ "IMP",
                               "cpase___7" ~ "other",
                               "cpase___0" ~ "C. auris",
                               "cpase___9" ~ "Unknown")) %>% 
  filter(cpase_value == 1) %>% 
  tableclean(2019, cpase, positive_id)

screendatacpase 

#Unit acuity
acquitydata <- screendata %>% 
  filter(!is.na(setting_acuity)) %>% 
  mutate(setting_acuity = case_match(as.integer(setting_acuity),
                                   1 ~ "yes",
                                   2 ~ "no",
                                   9 ~ "unknown")) %>% 
  tableclean(2019, setting_acuity, positive_id)
  

unitdata <- screendata %>% 
  filter(setting_acuity == 1) %>% 
  pivot_longer(cols = starts_with("setting_acuity_type"),
                            names_to = "setting1",
                            values_to = "settingvalue",
                            values_transform = list(settingvalue = as.integer)) %>% 
   mutate(setting1 = case_match(setting1, "setting_acuity_type___1" ~ "ICU",
                                     "setting_acuity_type___2" ~ "Burn",
                                     "setting_acuity_type___3" ~ "Vent",
                                     "setting_acuity_type___4" ~ "Oncology",
                                     "setting_acuity_type___7" ~ "Other",
                               "setting_acuity_type___9" ~ "Unknown")) %>% 
  filter(settingvalue == 1) %>% 
  tableclean(2019, setting1, positive_id)

unitdata

#int hospitalization
inthosdata <- screendata %>% 
  mutate(international = case_match(as.integer(intl_hosp), 
                                    0 ~ "No history of international hospitalization/care",
                                    1 ~ "History of international hospitalization/care")) %>% 
  tableclean(2019, international, positive_id)
  
inthosdata

#screen type
#screentypedata <- screendata %>% 
#  pivot_longer(cols = starts_with("screen_type"),
#                            names_to = "screening_type",
#                            values_to = "screening_type_value",
#                            values_transform = list(screening_type_value = as.integer)) %>% 
#  mutate(screening_type = case_match(screening_type, "screen_type___1" ~ "pps",
#                                     "screen_type___2" ~ "ID_contact",
#                                     "screen_type___3" ~ "flag_contact",
#                                     "screen_type___7" ~ "other",
#                                     "screen_type___9" ~ "unknown")) %>% 
#  filter(screening_type_value == 1) %>% 
#  tableclean(2019, screening_type, positive_id)

#screentypedata

#Index risk factors
screenriskdata <- screendata %>% 
  pivot_longer(cols = starts_with("index_lda"),
                            names_to = "risk_factor",
                            values_to = "risk_factor_value",
                            values_transform = list(risk_factor_value = as.integer)) %>% 
  mutate(risk_factor = case_match(risk_factor, "index_lda___1" ~ "open/draining wounds",
                                     "index_lda___2" ~ "ET/NT/Tracheostomy",
                                     "index_lda___3" ~ "central lines (inc. PICCs)",
                                     "index_lda___4" ~ "other indwelling devices",
                                     "index_lda___5" ~ "immunocompromised",
                                     "index_lda___6" ~ "diagnosed with other MDROs",
                                     "index_lda___7" ~ "international healthcare or travel",
                                     "index_lda___0" ~ "none",
                                     "index_lda___9" ~ "unknown")) %>% 
  filter(risk_factor_value == 1) %>% 
  tableclean(2019, risk_factor, positive_id)

screenriskdata

#precautions

precautiondata <- screendata %>% 
  mutate(cp_ebp = case_match(as.integer(cp_ebp),
                             1 ~ "yes",
                             0 ~ "no",
                             9 ~ "unknown",
                             NA ~ "unknown")) %>% 
  tableclean(2019, cp_ebp, positive_id)

precautiondata

#Pan Resistance
resistancedata <- screendata %>% 
  mutate(pns = case_match(as.integer(pns),
                          1 ~ "yes",
                          2 ~ "no",
                          NA ~ "unknown")) %>% 
  tableclean(2019, pns, positive_id)

resistancedata

#ADLS
adldata <- screendata %>% 
  mutate(index_assist = case_match(as.integer(index_assist),
                                   1 ~ "yes",
                                   2 ~ "no",
                                   3 ~ "unknown")) %>% 
  tableclean(2019, index_assist, positive_id)

adldata

#Common area
areadata <- screendata %>% 
  mutate(index_commonareas = case_match(as.integer(index_commonareas),
                                        1 ~ "yes",
                                        2 ~ "no",
                                        9 ~ "unknown")) %>% 
  tableclean(2019, index_commonareas, positive_id)

areadata

#groups of risk factors
groupedriskfactors <- screendata %>% 
  filter(!index_lda___9 == 1) %>% 
  select(-c("index_lda___0", "index_lda___9")) %>% 
  pivot_longer(cols = starts_with("index_lda"),
                            names_to = "risk_factor",
                            values_to = "risk_factor_value",
                            values_transform = list(risk_factor_value = as.integer)) %>% 
  mutate(risk_factor = case_match(risk_factor, "index_lda___1" ~ "open/draining wounds",
                                     "index_lda___2" ~ "ET/NT/Tracheostomy",
                                     "index_lda___3" ~ "central lines (inc. PICCs)",
                                     "index_lda___4" ~ "other indwelling devices",
                                     "index_lda___5" ~ "immunocompromised",
                                     "index_lda___6" ~ "diagnosed with other MDROs",
                                     "index_lda___7" ~ "international healthcare or travel")) %>%
  group_by(screening_id) %>% 
  mutate(risk_factor_sum = as.character(sum(risk_factor_value)),
         risk_factor_sum = case_when(risk_factor_sum == 0 ~ "none",
                                     risk_factor_sum == 1 ~ "1",
                                     risk_factor_sum == 2 ~ "2",
                                     risk_factor_sum >= 3 ~ ">=3")) %>% 
  ungroup()%>% 
  distinct(screening_id, .keep_all = T) %>% 
  tableclean(2019, risk_factor_sum, positive_id)

groupedriskfactors 
```

#### Table 1 generation

```{r, echo=FALSE}
#Table1
table1 <- rbind(screendataorg, screentypedata, screendatacpase, inthosdata, unitdata, screenriskdata, settingcount, resistancedata, precautiondata, acquitydata, totalcount, groupedriskfactors)

colnames(table1)[c(1,7:17)] <- c("Index organism","Screening activity", "Index case mechansim", "History of travel", "High acuity units", "Index case risk factors", "Facility type", "Is index organism Pan-R","On appropriate of precautions for entire duration of stay?", "Was index patient on high acuity unit?", "Screening results", "Number of risk factors present")

table1groups <- c("Screening results","Screening activity", "Index organism", "Index case mechansim", "Is index organism Pan-R", "Facility type", "Was index patient on high acuity unit?", "High acuity units", "History of travel", "On appropriate of precautions for entire duration of stay?", "Index case risk factors","Number of risk factors present")

#table1groups1 <-table1groups[!table1groups %in% c( "Index case risk factors", "Screening results")]

table1 <- table1 %>% 
  pivot_longer(cols = where(is.character),
               names_to = "group",
               values_to = "Measure",
               values_drop_na = T)

table1 <- table1[,c(6,7,1,4,2,5,3)]

gttab1 <- table1 %>% 
  arrange(desc(total)) %>%
  gt(rowname_col = "Measure",groupname_col = "group", row_group_as_column = T) %>% 
  row_group_order(groups = table1groups) 

gttab1 <- gttab1 %>% 
  cols_label(Measure = md("**Measure**"),
    Negative_screen = md("**Negative screen**"),
    Negative_perc = md("**%**"),
    Positive_screen = md("**Positive screen**"),
    Positive_perc = md("**%**"),
    total = md("**Total**")) %>% 
  opt_stylize(style = 2) %>% 
    tab_header(title = "Table 1",
               subtitle = "Counts for screening activities") %>% 
  tab_footnote(footnote = "Footnote")


#summary_rows(
#    columns = c(Negative_screen, Positive_screen, total),
#    fns = list(total = ~sum(.,na.rm= T))) %>% 
#  summary_rows(
#               fns = list(total = ~ round(sum(table1$Negative_screen)/sum(table1$total)*100,2)), columns = c(Negative_perc)) %>% 
#  summary_rows(
#               fns = list(total = ~ round(sum(table1$Positive_screen)/sum(table1$total)*100,2)), columns = c(Positive_perc)) 

gttab1
```

### Table 2

#### Raw Table 2

```{r, include=FALSE}
#screendata2 <- screendata %>% filter(screen_type___1 == 1, !screening_id %in% c("103906387 Durham C auris Duke June 2024")) #this is excluded because a positive was id from contact, not pps 

screendata2 <- screendata %>% filter(screen_type___1 == 1)

screendata2[screendata2$screening_id=="103906387 Durham C auris Duke June 2024", "positive_id"] <- "Negative_screen" #manually change this to negative for PPS table.

totalcount2 <- screendata2 %>% tableclean(2019, positive_id)
totalcount2$summary <- "summary"
#Setting Counts - type of healthcare facility where screening occurred

settingcount2 <- tableclean(screendata2, 2019, setting, positive_id)

settingcount2


#organism count for 2024


screendataorg2 <- screendata2 %>% 
  pivot_longer(cols = starts_with("organism__"),
                            names_to = "organism",
                            values_to = "organism_value",
                            values_transform = list(organism_value = as.integer)) %>% 
  mutate(organism = case_match(organism, "organism___1" ~ "C. auris",
                                     "organism___2" ~ "E. coli",
                                     "organism___3" ~ "E. cloacae",
                                     "organism___4" ~ "E. aerogenes",
                                     "organism___5" ~ "K. pneumoniae",
                               "organism___6" ~ "K. oxytoca",
                               "organism___7" ~ "P. aeruginosa",
                               "organism___8" ~ "A. baumanii",
                               "organism___9" ~ "No org id",
                               "organism___10" ~ "Other")) %>% 
  filter(organism_value==1) %>% 
  tableclean(2019, organism, positive_id)

screendataorg2

#cpase
screendatacpase2 <- screendata2 %>% 
  pivot_longer(cols = starts_with("cpase__"),
                            names_to = "cpase",
                            values_to = "cpase_value",
                            values_transform = list(cpase_value = as.integer)) %>% 
  mutate(cpase = case_match(cpase, "cpase___1" ~ "KPC",
                                     "cpase___2" ~ "NDM",
                                     "cpase___3" ~ "OXA23/24",
                                     "cpase___4" ~ "OXA-48",
                                     "cpase___5" ~ "VIM",
                               "cpase___6" ~ "IMP",
                               "cpase___7" ~ "other",
                               "cpase___0" ~ "C. auris",
                               "cpase___9" ~ "Unknown")) %>% 
  filter(cpase_value == 1) %>% 
  tableclean(2019, cpase, positive_id)

screendatacpase2

#Unit acuity
acquitydata2 <- screendata2 %>% 
  filter(!is.na(setting_acuity)) %>% 
  mutate(setting_acuity = case_match(as.integer(setting_acuity),
                                   1 ~ "yes",
                                   2 ~ "no",
                                   9 ~ "unknown")) %>% 
  tableclean(2019, setting_acuity, positive_id)

unitdata2 <- screendata2 %>% 
  filter(setting_acuity == 1) %>% 
  pivot_longer(cols = starts_with("setting_acuity_type"),
                            names_to = "setting1",
                            values_to = "settingvalue",
                            values_transform = list(settingvalue = as.integer)) %>% 
   mutate(setting1 = case_match(setting1, "setting_acuity_type___1" ~ "ICU",
                                     "setting_acuity_type___2" ~ "Burn",
                                     "setting_acuity_type___3" ~ "Vent",
                                     "setting_acuity_type___4" ~ "Oncology",
                                     "setting_acuity_type___7" ~ "Other",
                               "setting_acuity_type___9" ~ "Unknown")) %>% 
  filter(settingvalue == 1) %>% 
  tableclean(2019, setting1, positive_id)

unitdata2

#int hospitalization
inthosdata2 <- screendata2 %>% 
  mutate(international = case_match(as.integer(intl_hosp), 
                                    0 ~ "No history of international hospitalization/care",
                                    1 ~ "History of international hospitalization/care")) %>% 
  tableclean(2019, international, positive_id)
  
inthosdata2

#screen type
screentypedata2 <- screendata2 %>% 
  pivot_longer(cols = starts_with("screen_type"),
                            names_to = "screening_type",
                            values_to = "screening_type_value",
                            values_transform = list(screening_type_value = as.integer)) %>% 
  mutate(screening_type = case_match(screening_type, "screen_type___1" ~ "pps",
                                     "screen_type___2" ~ "ID_contact",
                                     "screen_type___3" ~ "flag_contact",
                                     "screen_type___7" ~ "other",
                                     "screen_type___9" ~ "unknown")) %>% 
  filter(screening_type_value == 1) %>% 
  tableclean(2019, screening_type, positive_id)

screentypedata2

#Index risk factors
screentypedata2 <- screendata2 %>% 
  pivot_longer(cols = starts_with("index_lda"),
                            names_to = "risk_factor",
                            values_to = "risk_factor_value",
                            values_transform = list(risk_factor_value = as.integer)) %>% 
  mutate(risk_factor = case_match(risk_factor, "index_lda___1" ~ "open/draining wounds",
                                     "index_lda___2" ~ "ET/NT/Tracheostomy",
                                     "index_lda___3" ~ "central lines (inc. PICCs)",
                                     "index_lda___4" ~ "other indwelling devices",
                                     "index_lda___5" ~ "immunocompromised",
                                     "index_lda___6" ~ "diagnosed with other MDROs",
                                     "index_lda___7" ~ "international healthcare or travel",
                                     "index_lda___0" ~ "none",
                                     "index_lda___9" ~ "unknown")) %>% 
  filter(risk_factor_value == 1) %>% 
  tableclean(2019, risk_factor, positive_id)

screentypedata2

#precautions

precautiondata2 <- screendata2 %>% 
  mutate(cp_ebp = case_match(as.integer(cp_ebp),
                             1 ~ "yes",
                             0 ~ "no",
                             9 ~ "unknown",
                             NA ~ "unknown")) %>% 
  tableclean(2019, cp_ebp, positive_id)

precautiondata2

#Pan Resistance
resistancedata2 <- screendata2 %>% 
  mutate(pns = case_match(as.integer(pns),
                          1 ~ "yes",
                          2 ~ "no",
                          NA ~ "unknown")) %>% 
  tableclean(2019, pns, positive_id)

resistancedata2

#ADLS
adldata2 <- screendata2 %>% 
  mutate(index_assist = case_match(as.integer(index_assist),
                                   1 ~ "yes",
                                   2 ~ "no",
                                   3 ~ "unknown")) %>% 
  tableclean(2019, index_assist, positive_id)

adldata2

#Common area
areadata2 <- screendata2 %>% 
  mutate(index_commonareas = case_match(as.integer(index_commonareas),
                                        1 ~ "yes",
                                        2 ~ "no",
                                        9 ~ "unknown")) %>% 
  tableclean(2019, index_commonareas, positive_id)

areadata2

#Grouped risk factors
groupedriskfactors2 <- screendata2 %>%
  filter(!index_lda___9 == 1) %>% 
  select(-c("index_lda___0", "index_lda___9")) %>% 
  pivot_longer(cols = starts_with("index_lda"),
                            names_to = "risk_factor",
                            values_to = "risk_factor_value",
                            values_transform = list(risk_factor_value = as.integer)) %>% 
  mutate(risk_factor = case_match(risk_factor, "index_lda___1" ~ "open/draining wounds",
                                     "index_lda___2" ~ "ET/NT/Tracheostomy",
                                     "index_lda___3" ~ "central lines (inc. PICCs)",
                                     "index_lda___4" ~ "other indwelling devices",
                                     "index_lda___5" ~ "immunocompromised",
                                     "index_lda___6" ~ "diagnosed with other MDROs",
                                     "index_lda___7" ~ "international healthcare or travel")) %>% 
 
  group_by(screening_id) %>% 
  mutate(risk_factor_sum = as.character(sum(risk_factor_value)),
         risk_factor_sum = case_when(risk_factor_sum == 0 ~ "none",
                                     risk_factor_sum == 1 ~ "1",
                                     risk_factor_sum == 2 ~ "2",
                                     risk_factor_sum >= 3 ~ ">=3")) %>% 
  ungroup()%>% 
  distinct(screening_id, .keep_all = T) %>% 
  tableclean(2019, risk_factor_sum, positive_id)

groupedriskfactors2
```

#### Table 2 generation

```{r, echo=FALSE}
#Table2
table2 <- rbind(screendataorg2, screendatacpase2, inthosdata2, unitdata2, screentypedata2, settingcount2, resistancedata2,precautiondata2, acquitydata2, totalcount2, groupedriskfactors2)

colnames(table2)[c(1,7:16)] <- c("Index organism", "Index case mechansim", "History of travel", "High acquity units", "Index case risk factors", "Facility type", "Is index organism Pan-R","On appropriate of precautions for entire duration of stay?", "Was index patient on high acuity unit?", "Screening results", "Number of risk factors present")

table2groups <- c("Screening results", "Index organism", "Index case mechansim", "Is index organism Pan-R", "Facility type", "Was index patient on high acuity unit?", "High acquity units", "History of travel", "On appropriate of precautions for entire duration of stay?", "Index case risk factors", "Number of risk factors present")

table2 <- table2 %>% 
  pivot_longer(cols = where(is.character),
               names_to = "group",
               values_to = "Measure",
               values_drop_na = T)

table2 <- table2[,c(6,7,1,4,2,5,3)]

gttab2 <- table2 %>% 
  arrange(desc(total)) %>% 
  gt(rowname_col = "Measure",groupname_col = "group", row_group_as_column = T) %>% 
  row_group_order(groups = table2groups) 

gttab2 <- gttab2 %>% 
  cols_label(Measure = md("**Measure**"),
    Negative_screen = md("**Negative screen**"),
    Negative_perc = md("**%**"),
    Positive_screen = md("**Positive screen**"),
    Positive_perc = md("**%**"),
    total = md("**Total**")) %>% 
  opt_stylize(style = 2) %>% 
    tab_header(title = "Table 2",
               subtitle = "Counts for screening activities which include a PPS") %>% 
  tab_footnote(footnote = "Footnote")

#summary_rows(fns = list(total = ~ round(sum(table1$Negative_screen)/sum(table1$total)*100,2)), columns = c(Negative_perc)) %>% 
#  summary_rows(fns = list(total = ~ round(sum(table1$Positive_screen)/sum(table1$total)*100,2)), columns = c(Positive_perc)) %>%  
#  summary_rows(columns = c(Negative_screen, Positive_screen, total),
#               fns = list(total = ~sum(.,na.rm= T))) 

gttab2
```

### Table 3 Continuous variables

#### Date data

```{r, include=FALSE}
timelist <- c("timetoreport", "timetoppsreportdate", "timetoppsmdrodate")

datetable <- mutate_at(screendata2, vars(contains("date")), mdy)

timedata <- datetable %>% 
  mutate(timetoreport = as.numeric(abs(difftime(datetable$report_date, datetable$mdro_date, units = "days"))),
         timetoppsreportdate =  as.numeric(abs(difftime(datetable$pps_date, datetable$report_date, units = "days"))),
         timetoppsmdrodate =  as.numeric(abs(difftime(datetable$pps_date, datetable$mdro_date, units = "days")))) %>% 
  drop_na(timelist)

timesummary <- function(dataset,value_col, group_col){
 
  summary_stats <- dataset %>%
    mutate(q1 = quantile({{ value_col }}, 0.25, na.rm = TRUE),
           q3 = quantile({{ value_col }}, 0.75, na.rm = TRUE),
           iqr = q3 - q1,
           lower_bound = q1 - 1.5 * iqr,
           upper_bound = q3 + 1.5 * iqr) %>%
    # Filter out the outliers
    filter({{ value_col }} >= lower_bound & {{ value_col }} <= upper_bound) %>%
    group_by({{ group_col }}) %>% 
    # Summarize the remaining data
    summarise(mean = mean({{ value_col }}, na.rm = TRUE),
              median = median({{ value_col }}, na.rm = TRUE))

  return(summary_stats)
  
}

timeoutput1 <- map_df(timelist, ~{timedata %>%
                   timesummary(value_col = !!sym(.x), group_col = positive_id) %>% 
                   mutate(timeperiod = .x)})

timeouput2 <- map_df(timelist, ~{timedata %>%
    filter(organism___8 == 0) %>% 
    timesummary(value_col = !!sym(.x), group_col = positive_id) %>% 
    mutate(timeperiod = paste("CRAB removed", .x))})

timeoutput <- rbind(timeoutput1, timeouput2)

timeoutput <- timeoutput %>% 
  pivot_longer(c("mean", "median"), names_to = "Stat", values_to = "test2") %>% 
  pivot_wider(names_from = "positive_id", values_from = "test2")
```

#### Amount of people tested

```{r, include=FALSE}

amtoutput1 <- screendata2 %>% 
  timesummary(value_col = as.numeric(pps_denom_p1), group_col = positive_id) %>% 
  mutate(timeperiod = "Persons tested during PPS")

posonly <- screendata2 %>% 
  filter(positive_id == "Positive_screen")

amtoutput2 <- posonly %>% 
  timesummary(pps_totalpos_p1) %>% 
  mutate(positive_id = "Positive_screen",
         timeperiod = "Amt positive during first")

amtoutput <- rbind(amtoutput1, amtoutput2)

amtoutput <- amtoutput %>% 
  pivot_longer(c("mean", "median"), names_to = "Stat", values_to = "test2") %>% 
  pivot_wider(names_from = "positive_id", values_from = "test2")


#per unit
amtunit <- screendata2 %>%
  group_by(setting) %>% 
  summarise(total = sum(pps_denom_p1, na.rm = T),
            #totalpossame = sum(pps_num_p1, na.rm = T),
            #totalposany = sum(pps_num_total, na.rm = T),
            median = median(as.numeric(pps_denom_p1), na.rm = T),
            #medianpossame = median(as.numeric(pps_num_p1), na.rm = T),
            #medianposany = median(as.numeric(pps_num_total), na.rm = T),
            mean = mean(as.numeric(pps_denom_p1), na.rm = T),
            min = min(pps_denom_p1, na.rm = T),
            max = max(pps_denom_p1, na.rm = T),
            range = max - min)
            #meanpossame = mean(as.numeric(pps_num_p1), na.rm = T),
            #meanposany = mean(as.numeric(pps_num_total), na.rm = T))

amtunitrange <- screendata2 %>%
  group_by(setting) %>% 
  summarise(range = range(as.numeric(pps_denom_p1), na.rm = T),
            rangepossame = range(as.numeric(pps_num_p1), na.rm = T),
            rangeposany = range(as.numeric(pps_num_total), na.rm = T)) 
```

#### Table 3 generation

```{r, echo=FALSE}
table3 <- rbind(timeoutput, amtoutput) #combine our outputs from ###date data


table3timeperiodnames <- rep(c("Time from lab result to report in NCEDSS", "Time to perform PPS from report in NCEDSS date", "Time to perform PPS from lab result", "CRAB removed: Time from lab result to report in NCEDSS", "CRAB removed: Time to perform PPS from report in NCEDSS date", "CRAB removed: Time to perform PPS from lab result", "Amount of patients tested during first PPS", "Amount of patients who tested positive during first PPS"), each = 2) #We need to make the names in table3$timeperiod make more sense. this solution is very dumb and could be solved by fixing previous code names, we repeat this list twice so it is the same vector as table3$timeperiod.

table3$timeperiod <- table3timeperiodnames #Here we match and replace our old names with our new names

gttable3 <- table3 %>% 
  gt(groupname_col = "timeperiod", row_group_as_column = T) 

gttable3 %>% opt_stylize(style = 2) %>% 
    tab_header(title = "Table 3 - Time data (days)",
               subtitle = "") %>% 
  tab_footnote(footnote = "Footnote") %>% 
  fmt_number(decimals = 2)

```

#### Table 4 generation Setting burden

```{r, echo=FALSE}
gttable32 <- amtunit %>% 
  gt(row_group_as_column = T) 

gttable32 %>% opt_stylize(style = 2) %>% 
    tab_header(title = "Table 4 - Facility Burden",
               subtitle = "Number of patients tested per facility type") %>% 
  tab_footnote(footnote = "Footnote") %>% 
  fmt_number(decimals = 2)
```

#### Screening cases per month

```{r, echo=FALSE}
datetrend <- timedata %>% 
  mutate(monyr = floor_date(pps_date, "month")) %>% 
  group_by(monyr) %>% 
  summarise(total = sum(pps_denom_p1, na.rm = T))

datetrend %>% 
  ggplot(aes(x = monyr, y = total))+
  geom_bar(stat = "identity")+
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b %Y")+
  theme(axis.text.x = element_text(angle = 30, hjust = 1))
```

## Risk

```{r, include=FALSE}

```
